sta:
	g++ -static -s -g backgammon.cpp class.cpp function.cpp -o backgammon.exe -DSFML_STATIC -I f:\CC++\Backgammon\SFML\include -L f:\CC++\Backgammon\SFML\lib -lsfml-graphics-s -lsfml-audio-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32 -lfreetype -ljpeg -lflac -logg -lvorbis -lvorbisfile -lvorbisenc
move:
	g++ -g backgammon.cpp class.cpp function.cpp -o backgammon.exe -I f:\CC++\Backgammon\SFML\include -L f:\CC++\Backgammon\SFML\lib -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system